-- Tabela de palpites para o Bolão Brasil x Japão
CREATE TABLE IF NOT EXISTS public.palpites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    nome TEXT NOT NULL CHECK (char_length(nome) >= 2),
    gols_brasil INTEGER NOT NULL CHECK (gols_brasil >= 0),
    gols_japao INTEGER NOT NULL CHECK (gols_japao >= 0),
    -- Trava de segurança para impedir palpites após as 13:55 (UTC-3) de 29/06/2026
    CONSTRAINT limite_horario CHECK (created_at < '2026-06-29 13:55:00-03'::timestamptz)
);

-- Habilitar RLS (Row Level Security)
ALTER TABLE public.palpites ENABLE ROW LEVEL SECURITY;

-- Política para permitir que qualquer pessoa insira um palpite
CREATE POLICY "Permitir inserção pública" 
ON public.palpites 
FOR INSERT 
TO public 
WITH CHECK (true);

-- Política para permitir que qualquer pessoa leia os palpites
CREATE POLICY "Permitir leitura pública" 
ON public.palpites 
FOR SELECT 
TO public 
USING (true);
